theme: jekyll-theme-minimal
title: Game of Comparch
description: An exploration and implementation of cellular automata and computing for Olin College Computer Architecture FA18.
baseurl: /game-of-comparch
